### ISSUE TITLE
有考虑过模拟滑动吗

### ISSUE THREAD

**Issue by Fordeson** [didi/DiDiPrism#12]
rt

**Comment by ronghaopger** [comment]
支持模拟滑动的主要问题是产生的数据量过大但在目前的应用场景下又没有太多价值，之前也回答过类似的问题：https://github.com/didi/DiDiPrism/issues/6#issuecomment-742200419
在2021年我们会考虑加入，会放置一个开关来选择是否开启滑动支持。

**Comment by Fordeson** [comment]
我们也在做类似的模拟操作方案，考虑到100%模拟操作的话，加上滑动效果会好很多。

**Comment by ronghaopger** [comment]
嗯，有场景且能产生价值很重要。 也期待下你的PR，接下来我们会支持。

**Comment by Fordeson** [comment]
还有网络模拟这一部分。目前通用方案是mock数据，还有一些客户端本地数据怎么处理，比如从userDefaults里面读取的前后不一样可能会导致UI不一样，还有数据库、其他涉及到存储的方式等等。不知道你们有没有一个系统的解决方案。

**Comment by ronghaopger** [comment]
网络数据支持mock，可以通过trace id 请求原始数据来替换 或者 直接传入原始数据。
其他的本地化数据还没有涉及，本地化数据直接影响UI的例子不多吧？

**Comment by Fordeson** [comment]
我们有在做本机型的回放数据可以移植到其他任何机型。考虑类似于ABTest这种的本地数据会对UI影响比较大。

**Comment by ronghaopger** [comment]
这种场景下走统一的mock平台会好一些吧？ 来回移植本地数据不实际吧。
ABTest核心还是网络数据，总不能是本地一个变量决定吧。
