### ISSUE TITLE
关于如何使用的问题

### ISSUE THREAD

**Issue by wenxuehai** [didi/DiDiPrism#13]
你好，我是H5开发的，对于原生APP开发不太了解。想请教一下几个问题：

1、这个操作行为回放是怎么做到的，是以视频的方式存放下来的还是怎么样？
2、如何将小桔棱镜应用到项目当中，生成的文字回放和操作行为回放是存放在哪里的，我们应该如何取到这些信息
3、听说后续会支持移动端H5，请问一下预估什么时候可以支持呢？

盼回复，谢谢！

**Comment by ronghaopger** [comment]
你好，我依次回答你：
1、不是存视频的方式，是通过生成指令再通过指令驱动APP运行的方式来实现。
2、你如果熟悉iOS或者Android开发，可以简单使用下demo，SDK会把生成的指令传出来，具体使用方式就靠大家各自定制了。
3、2021年初我们尽可能放出来一个简单版本。

**Comment by wenxuehai** [comment]
你好，请问有web端吗，或者后续有没有打算支持web端，是否有这个计划呢，谢谢

**Comment by ronghaopger** [comment]
> 你好，请问有web端吗，或者后续有没有打算支持web端，是否有这个计划呢，谢谢

你好，短期内没有支持Web端的计划。可以在GitHub上搜索一些专门支持Web端的方案，听别人提到过。
