### ISSUE TITLE
应用场景落地方案讨论

### ISSUE THREAD

**Issue by lcddhr** [didi/DiDiPrism#19]
首先感谢开源, 学习到挺多，有一些疑问想和你们交流交流~~

关于应用场景我这边能想到：
1. 操作回放是模拟用户真实操作, 你们线上目前是如何应用这个功能呢，目前这边脑洞了一下，可以模拟一些极端的测试用例, 对自动化测试有帮助
2. 采集到的文字行为有助于排查线上问题

你们能简单分享一下应用场景吗？

**Comment by ronghaopger** [comment]
感谢关注~
你提到的自动化测试场景和排查线上问题场景都是很好的想法，可以尝试落地。
还有比如助力产品迭代优化的场景，帮助消除我们与用户认知之间的鸿沟，提升用户体验。
再就是你还可以关注下另一块**操作检测能力**，合理运用也可以带来用户体验提升或者帮助创造商业价值。
我们内部具体的应用会在合适的时间分享出来。

**Comment by bullda** [comment]
操作检测具体是什么意思呢? 能不能以一个场景举例, 解释一下, 谢谢.

**Comment by ronghaopger** [comment]
> 操作检测具体是什么意思呢? 能不能以一个场景举例, 解释一下, 谢谢.

参考下这个文档： https://github.com/didi/DiDiPrism/blob/master/Doc/%E6%93%8D%E4%BD%9C%E6%A3%80%E6%B5%8B/%E6%93%8D%E4%BD%9C%E6%A3%80%E6%B5%8B%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E.md

**Comment by ronghaopger** [comment]
> 操作检测具体是什么意思呢? 能不能以一个场景举例, 解释一下, 谢谢.

参考下这个：  [操作检测 策略配置说明](https://github.com/didi/DiDiPrism/blob/master/Doc/%E6%93%8D%E4%BD%9C%E6%A3%80%E6%B5%8B/%E6%93%8D%E4%BD%9C%E6%A3%80%E6%B5%8B%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E.md)
