### ISSUE TITLE
请问可以应用在 Swift 项目中吗？

### ISSUE THREAD

**Issue by ReverseScale** [didi/DiDiPrism#2]
感谢大佬给我们开拓视野，请问关于“把埋点数据‘镶’在页面元素上”的功能，是不是暂时没有开源计划，如果开源是否会有相应的配套后台呢？

**Comment by ronghaopger** [comment]
1、可以的，Swift项目支持引入第三方OC库。
2、关于“把埋点数据‘镶’在页面元素上”的功能，我们正在筹备中（预计2021年初支持），开源思路应该是仅提供移动端可视化能力，支持接入方配置自己的数据源。不会有配套后台。
