### ISSUE TITLE
iOS：presentViewController后，回放失败

### ISSUE THREAD

**Issue by FirstDKS521** [didi/DiDiPrism#22]
问题1：
如果present一个导航栏控制器后，控制器里面添加一个按钮，点击按钮做dismiss操作，回放时失败；
看代码里面有单独对present的控制做处理，但是最终拿到的响应者为空，请问有方法解决吗？

问题2：
如果在当前window上面添加一个vc.view，而不是直接添加一个view，此时回放也是同样失败，此问题有好的方案吗？

**Comment by ronghaopger** [comment]
感谢反馈，我抽空看一下这两个问题。 也期待你的PR

**Comment by ronghaopger** [comment]
> 问题1：
> 如果present一个控制后，控制里面添加一个按钮，点击按钮做dismiss操作，回放时失败；
> 看代码里面有单独对present的控制做处理，但是最终拿到的响应者为空，请问有方法解决吗？
> 
> 问题2：
> 如果在当前window上面添加一个vc.view，而不是直接添加一个view，此时回放也是同样失败，此问题有好的方案吗？

方便把这两个问题的demo传给我吗？

**Comment by FirstDKS521** [comment]
尴尬了，我们的开发环境是内网，demo传不出来

问题1：
在DiDiPrism提供的iOS demo中，点击某个位置随便present出一个控制器即可，控制器里面添加一个按钮，点击按钮做dismiss操作

问题2：
在DiDiPrism提供的iOS demo中，在当前UIWindow上面添加一个vc.view，vc.view里面随便放个按钮，点击按钮removeFromeSuperview即可

**Comment by ronghaopger** [comment]
> 尴尬了，我们的开发环境是内网，demo传不出来
> 
> 问题1：
> 在DiDiPrism提供的iOS demo中，点击某个位置随便present出一个导航栏控制器即可，控制器里面添加一个按钮，点击按钮做dismiss操作
> 
> 问题2：
> 在DiDiPrism提供的iOS demo中，在当前UIWindow上面添加一个vc.view，vc.view里面随便放个按钮，点击按钮removeFromeSuperview即可

你好，问题1 和 问题2 在 0.1.1 中都已修复，感谢反馈。
