### ISSUE TITLE
如何复现用户的实际运行环境

### ISSUE THREAD

**Issue by xysT2W** [didi/DiDiPrism#24]
希望用这个开源工具来帮助检测用户在实际使用中的操作路径，但是每个用户的瞬时数据并不是一致的。所以同样的操作路径，不一定能在开发的环境中复现，请问这个问题有什么好的解决办法吗？

**Comment by ronghaopger** [comment]
> 希望用这个开源工具来帮助检测用户在实际使用中的操作路径，但是每个用户的瞬时数据并不是一致的。所以同样的操作路径，不一定能在开发的环境中复现，请问这个问题有什么好的解决办法吗？

棱镜目前在iOS侧提供了你提到的“瞬时数据”的记录和还原能力，但是需要后端服务的适配支持。

**Comment by ronghaopger** [comment]
> 希望用这个开源工具来帮助检测用户在实际使用中的操作路径，但是每个用户的瞬时数据并不是一致的。所以同样的操作路径，不一定能在开发的环境中复现，请问这个问题有什么好的解决办法吗？

可以关注下 `PrismRecordNSURLProtocol` `PrismReplayNSURLProtocol` 这两个类的实现。
