### ISSUE TITLE
棱镜的实际应用场景

### ISSUE THREAD

**Issue by laughingkid** [didi/DiDiPrism#3]
行为检测，行为回放。这些滴滴在实际的应用场景中，是怎么应用的？如果全链路启用，每天数据量多大。
基于这样的dsl，是否又web版的数据回放功能？

**Comment by ronghaopger** [comment]
很好的提问，遗憾我又不能很好的回答你。
1、应用场景的选择核心就是围绕创造用户价值和商业价值进行，内部的应用场景会在合适的时间介绍。（我们希望的是把能力开源出来，介绍给大家，大家可以天马行空的发挥它的价值）
2、关于数据量，跟业务量有关，无法确定回答。你可以跑一下demo，看看你的一组操作会产生多少数据量，就会有个预判。
3、移动端H5场景下我们是做了初级支持的，后续会开源出来。当然你期待你的贡献。
