### ISSUE TITLE
请问数据可视化模块代码在哪？

### ISSUE THREAD

**Issue by xiaodin1** [didi/DiDiPrism#31]
请问下数据可视化模块是否有计划开源呢？期待开源~感觉有数据后对回放发现的问题进行量化才能更好的服务产品~

**Comment by ronghaopger** [comment]
> 请问下数据可视化模块是否有计划开源呢？期待开源~感觉有数据后对回放发现的问题进行量化才能更好的服务产品~

可以跑一下demo，主要功能都能体验到。
