### ISSUE TITLE
iOS端Prism支持自动捕获的用户行为问题

### ISSUE THREAD

**Issue by BladeWayne** [didi/DiDiPrism#6]
iOS端Prism demo录制过程中，我注意到文本输入与列表滚动行为没有记录，当然回放同样没有，请问是feature还是bug？

**Comment by ronghaopger** [comment]
是feature.
1、文本输入可能涉及到隐私问题，我们是有目的的忽略（源码中有体现）。
2、列表滚动会产生较大的数据量，当前我们应用场景中实际价值又很小，所以暂时空缺。
最后，如果你们需要，可以贡献代码进来，方便其他同样需要的同学 :)
