### ISSUE TITLE
A android端Prism

### ISSUE THREAD

**Issue by sheng930920** [didi/DiDiPrism#8]
感谢大佬的开源给我们更好的开拓思维，小桔棱镜 Android SDK端现在最低是只支持到6.0系统、androidx，因为以前很多旧项目是使用support库开发最低要适配到5.0系统，整体升级迁移到androidx工作量比较大，而且不知道是否有其他不可控的问题，所以请问后期是否有考虑适配到5.0系统和支持使用使用support库呢

**Comment by EastWoodYang** [comment]
只支持到6.0系统，主要考虑到对window能简单的hook。如果要适配到5.0的话，可以在hook时自己做下适配，如果不收集弹窗类的，也可以直接使用ActivityLifecycleCallbacks来做，androidx转support库也很简单。总之，建议接入时还是做下符合各自场景的适配。
