### ISSUE TITLE
用例回放机型兼容

### ISSUE THREAD

**Issue by XXEgges** [didi/DiDiPrism#9]
还没来得及看源码，同一个用例支持多机型回放吗？

**Comment by ronghaopger** [comment]
支持的，试试Demo就知道啦。

**Comment by XXEgges** [comment]
666  哈 我有空学习，学习。我们内部也做了个类似的东西，基于状态机，目前支持页面自动分析，自动识别元素。机型适配和弹窗识别是个比较棘手的问题。
